export const statusDivorcio = {
  1: 'Início do serviço',
  2: 'Contrato pronto para assinatura',
  3: 'Pagamento parcial efetuado',
  4: 'Aguardando complementação de pagamento',
  5: 'Pagamento concluído',
  6: 'Contrato iniciado',
  7: 'Nota fiscal disponível para download',
  8: 'Envio de documentos',
  9: 'Minuta do divórcio',
  10: 'Aguardando envio do formulário',
  11: 'Aguardando agendamento de certificado de assinatura',
  12: 'Aguardando conjuge gerar certificado',
  13: 'Certificados gerados',
  14: 'Aguardando assinatura do documento',
  15: 'Documento assinado',
  16: 'Aguardando agendamento de conferência (audiência)',
  17: 'Aguardando agendamento do conjuge',
  18: 'Escritura de divórcio pronta - disponível para download',
};
